# Generated by Django 5.0.2 on 2024-02-12 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precent', models.FloatField(default=0)),
                ('is_global', models.BooleanField()),
                ('month', models.DateField(verbose_name='Месяц плана')),
                ('plan_sum', models.FloatField(default=0)),
                ('is_profit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subcategory', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycheck.subcategory')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycheck.category')),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_comment', models.CharField(max_length=100)),
                ('spend_sum', models.FloatField(default=0)),
                ('spend_date', models.DateTimeField(verbose_name='Дата расхода')),
                ('kod_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycheck.category')),
                ('kod_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycheck.subcategory')),
                ('kod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycheck.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_comment', models.CharField(max_length=100)),
                ('profit_sum', models.FloatField(default=0)),
                ('profit_date', models.DateTimeField(verbose_name='Дата расхода')),
                ('kod_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycheck.category')),
                ('kod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycheck.user')),
            ],
        ),
    ]
