# Generated by Django 5.0.2 on 2024-05-21 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precent', models.FloatField(default=0)),
                ('is_global', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('plan_sum', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cat_sum', models.FloatField(default=0)),
                ('is_profit', models.BooleanField(default=False)),
                ('date_upd_cat_sum', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneycheck.category')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneycheck.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(default=0)),
                ('comment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('kod_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycheck.category')),
            ],
        ),
    ]
