# Generated by Django 5.0.2 on 2024-05-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_global',
        ),
    ]
