# Generated by Django 5.0.2 on 2024-03-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='kod_category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='kod_category',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='kod_user',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='kod_subcategory',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='kod_user',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Profit',
        ),
        migrations.DeleteModel(
            name='Spending',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
