# Generated by Django 5.0.2 on 2024-06-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0002_remove_category_parent_remove_plan_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
