# Generated by Django 5.0.2 on 2024-03-07 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='kod_subcategory',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profit',
            old_name='profit_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='profit',
            old_name='profit_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='profit',
            old_name='kod_category',
            new_name='kod_cat',
        ),
        migrations.RenameField(
            model_name='profit',
            old_name='profit_sum',
            new_name='sum',
        ),
        migrations.RenameField(
            model_name='spending',
            old_name='spend_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='spending',
            old_name='spend_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='spending',
            old_name='kod_category',
            new_name='kod_cat',
        ),
        migrations.RenameField(
            model_name='spending',
            old_name='spend_sum',
            new_name='sum',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneycheck.category'),
        ),
        migrations.AddField(
            model_name='plan',
            name='cat_kod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneycheck.category'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
