# Generated by Django 5.0.2 on 2024-03-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0007_alter_spending_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_profit',
            field=models.BooleanField(default=False),
        ),
    ]
