# Generated by Django 5.0.2 on 2024-03-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0008_category_is_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
