# Generated by Django 5.0.2 on 2024-03-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0009_alter_spending_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
