# Generated by Django 5.0.2 on 2024-03-15 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0013_remove_plan_month_plan_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_profit',
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 15, 11, 55, 55, 108141, tzinfo=datetime.timezone.utc)),
        ),
    ]
