# Generated by Django 5.0.2 on 2024-03-15 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0014_remove_plan_is_profit_alter_plan_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='cat_kod',
            new_name='kod_cat',
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 15, 12, 8, 19, 593609, tzinfo=datetime.timezone.utc)),
        ),
    ]
