# Generated by Django 5.0.2 on 2024-03-15 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0015_rename_cat_kod_plan_kod_cat_alter_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 15, 12, 10, 45, 682339, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
