# Generated by Django 5.0.2 on 2024-03-15 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0018_alter_plan_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='kod_cat',
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 15, 15, 40, 25, 120151, tzinfo=datetime.timezone.utc)),
        ),
    ]
