# Generated by Django 5.0.2 on 2024-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0020_category_plan_alter_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
