# Generated by Django 5.0.2 on 2024-03-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0022_rename_spending_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
