# Generated by Django 5.0.2 on 2024-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0023_alter_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
