# Generated by Django 5.0.2 on 2024-04-30 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0026_remove_operation_user_category_user_delete_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneycheck.plan'),
        ),
    ]
