# Generated by Django 5.0.2 on 2024-05-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0027_alter_category_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_sum',
            field=models.FloatField(default=0),
        ),
    ]
