# Generated by Django 5.0.2 on 2024-05-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneycheck', '0028_category_cat_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_upd_cat_sum',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
